services:
  scraper:
    container_name: scrape-your-value-dev
    build: .
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro
    env_file: 
      - .env
