services:
  scrape-your-value:
    image: ghcr.io/xavierdupuis/scrapeyourvalue:main
    container_name: scrape-your-value
    restart: always
    environment:
      - CRON_SCHEDULE=${CRON_SCHEDULE:?Missing variable CRON_SCHEDULE}
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro